name: Build and Push Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build Docker image
        run: |
          docker build . -t django-blog .
      
      - name: Push Docker image
        run: docker push rehman9852/my-python-app:latest

      - name: Run tests
        run: |
         pip install pytest
          pytest
