name: Build and Push Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Docker images
        run: docker images
     
      - name: Log in to Docker Hub
        run: echo "${{ secrets.MY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.rehman9852 }}"
        env:
          DOCKER_USERNAME: ${{ secrets.rehman9852 }}
          DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
          
      - name: Build Docker image with 'latest' tag
        run: docker build -t rehman9852/my-django-app:latest .
      
      - name: Push Docker image with 'latest' tag
        run: docker push rehman9852/my-django-app:latest
